services:
  - type: web
    name: ats-resume-builder-python-ai
    env: python
    rootDir: python-ai
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
